name: "Generate SSH Config"
description: "Generate SSH Config"

branding:
  icon: 'terminal'
  color: 'gray-dark'

inputs:
  ssh_host:
    description: "SSH Host"
    required: true
  ssh_user:
    description: "SSH User"
    required: true
  ssh_port:
    description: "SSH Port"
    required: true
    default: 22
  ssh_key:
    description: "SSH Key"
    required: true

outputs:
  ssh_host_alias:
    description: "Name of the host that must be used to connect to this server"
    value: ${{ steps.ssh.outputs.ssh_host_alias }}

runs:
  using: "composite"
  steps:
    - name: Generate SSH Config
      id: ssh
      shell: bash
      run: |
        _SSH_HOST_ALIAS="host-$(cat /proc/sys/kernel/random/uuid)"
        _SSH_KEY=~/.ssh/${_SSH_HOST_ALIAS}
        mkdir -p ~/.ssh
        echo '${{ inputs.ssh_key }}' > ${_SSH_KEY}
        chmod 600 ${_SSH_KEY}
        printf "Host ${_SSH_HOST_ALIAS}\n\tHostName ${{ inputs.ssh_host }}\n\tUser ${{ inputs.ssh_user }}\n\tPort ${{ inputs.ssh_port }}\n\tIdentityFile ${_SSH_KEY}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        ssh -q ${_SSH_HOST_ALIAS} '
          echo "Test SSH OK"
        '
        echo "ssh_host_alias=${_SSH_HOST_ALIAS}" >> ${GITHUB_OUTPUT}
